#!/bin/sh

if [ -z "$REPOSITORY" -o -z "$BRANCH" ]; then
  echo "REPOSITORY and BRANCH should be set to a Git repository and a branch name"
  exit 1
fi

STAGE="tmp/lectures-repo"
TARGET="$STAGE/compiled-lectures"

if [ ! -d $STAGE ]; then
  git clone $REPOSITORY $STAGE
fi

pushd $STAGE

git checkout $BRANCH
git pull
make

popd

if [ ! -d $TARGET ]; then
  echo "Expected the lectures to be compiled in $TARGET, but nothing found"
  exit 1
fi

echo "Copying to public/lectures..."
mkdir -p public/lectures
rm -rf public/lectures/*
cp -r $TARGET/* public/lectures
