#!/bin/sh

if [ ! -d tmp/ruby-lectures ]; then
  git clone https://github.com/fmi/ruby-lectures.git tmp/ruby-lectures
fi

cd tmp/ruby-lectures

git pull
bundle install
rm -rf compiled
bundle exec thor rebuild

cd ../..

echo "Copying public/lectures..."
[ -f public/lectures/* ] && rm -rf public/lectures/*
cp -r tmp/ruby-lectures/compiled public/lectures
